/**
 * TEDS — Tree-Edit-Distance-based Similarity for table HTML.
 *
 * A faithful TypeScript port of the reference metric from IBM PubTabNet
 * (https://github.com/ibm-aur-nlp/PubTabNet, src/metric.py, commit
 * 8ffde9024bd331f5a61c3c549fdf30dd3c3e43a5), with zero runtime dependencies.
 *
 * Tree model (mirrors the reference `TableTree` built by `load_html_tree`):
 *   - element nodes under <table> in document order: table, thead, tbody,
 *     tfoot, tr, td (a <th> is normalized to td — all producers in this
 *     benchmark emit header cells as plain cells, and the reference is run
 *     with the same rewrite when generating fixtures);
 *   - td nodes carry {colspan, rowspan, content}; other nodes carry tag only.
 *
 * Cost model (reference `CustomConfig`):
 *   - insert = delete = 1;
 *   - rename(a, b) = 1 if tag, colspan, or rowspan differ; otherwise, for two
 *     td nodes with any content, levenshtein(contentA, contentB) / max(len);
 *     otherwise 0. In structureOnly mode cell content is treated as empty, so
 *     matching-span td pairs rename for free.
 *
 * Score (reference `TEDS.evaluate`):
 *   TEDS = 1 - editDistance / max(descendantCount(pred), descendantCount(gt))
 * where descendantCount counts every element node strictly below <table>
 * (the reference counts `table.xpath(".//*")`, which excludes the table root
 * even though the root participates in the edit distance). Empty or
 * unparseable input on either side scores 0.
 *
 * Documented normalizations (differences from raw lxml parsing, chosen so all
 * benchmark producers compare on equal footing; the committed fixtures were
 * generated by running the Python reference on identically-normalized input):
 *   - inline formatting tags inside cells (<b>, <i>, <sub>, <sup>, <span>,
 *     <br>, ...anything non-structural) are stripped, keeping their text —
 *     equivalent to running the reference with ignore_nodes=(those tags),
 *     which applies lxml's etree.strip_tags before building the tree;
 *   - <th> is treated as <td> (see above);
 *   - cell text has HTML entities decoded and whitespace runs collapsed to a
 *     single space, then is trimmed;
 *   - text outside cells (indentation between structural tags) is ignored,
 *     matching the reference, which never tokenizes non-td text.
 *
 * Algorithm: Zhang–Shasha tree edit distance (K. Zhang & D. Shasha, 1989)
 * rather than APTED. Both are *exact* optimal tree-edit-distance algorithms
 * for arbitrary per-node cost functions, so they return identical distances;
 * APTED only improves the worst-case constant/complexity. Zhang–Shasha runs
 * O(n1·n2·min(depth1,leaves1)·min(depth2,leaves2)) — table trees are ~3 deep,
 * so scoring a pair of ~2000-node trees takes well under a second. Cell-pair
 * string edit distances are memoized. Levenshtein operates on Unicode code
 * points to match Python's `list(text)` semantics.
 */

interface TableNode {
  tag: string;
  /** -1 for non-td nodes (mirrors Python None; -1 === -1 keeps rename at 0). */
  colspan: number;
  rowspan: number;
  /** Cell text for td nodes, null otherwise. */
  content: string | null;
  children: TableNode[];
}

/** Tags that become tree nodes; everything else inside <table> is inline. */
const STRUCTURAL = new Set(['table', 'thead', 'tbody', 'tfoot', 'tr', 'td']);

const NAMED_ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
};

function decodeEntities(text: string): string {
  return text.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]*);/g, (whole, body: string) => {
    if (body[0] === '#') {
      const hex = body[1] === 'x' || body[1] === 'X';
      const code = parseInt(body.slice(hex ? 2 : 1), hex ? 16 : 10);
      return Number.isFinite(code) && code >= 0 && code <= 0x10ffff ? String.fromCodePoint(code) : whole;
    }
    const named = NAMED_ENTITIES[body.toLowerCase()];
    return named !== undefined ? named : whole;
  });
}

function normalizeCellText(raw: string): string {
  return decodeEntities(raw).replace(/\s+/g, ' ').trim();
}

/** A parsed markup token: an open/close/self-closing tag. */
interface TagToken {
  name: string;
  closing: boolean;
  attrs: string;
  /** index just past the token in the source */
  end: number;
}

/** Parse the tag starting at `<` position `at`; null if malformed. */
function parseTag(src: string, at: number): TagToken | null {
  const m = /^<(\/?)([a-zA-Z][a-zA-Z0-9]*)((?:"[^"]*"|'[^']*'|[^>"'])*)\/?>/.exec(src.slice(at));
  if (!m) return null;
  return { name: m[2].toLowerCase(), closing: m[1] === '/', attrs: m[3], end: at + m[0].length };
}

function parseSpan(attrs: string, name: string): number {
  const m = new RegExp(`${name}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'>]+))`, 'i').exec(attrs);
  if (!m) return 1;
  const v = parseInt((m[1] ?? m[2] ?? m[3]).trim(), 10);
  return Number.isFinite(v) && v > 0 ? v : 1;
}

/**
 * Parse the first <table> element from an HTML string into a TableNode tree.
 * Restricted-subset parser: structural tags become nodes, inline tags inside
 * cells are stripped keeping text, comments are dropped. Returns null when no
 * parseable table exists.
 */
export function parseTableHtml(htmlStr: string): TableNode | null {
  const start = htmlStr.search(/<table[\s>/]/i);
  if (start < 0) return null;

  const root: TableNode = { tag: 'table', colspan: -1, rowspan: -1, content: null, children: [] };
  const stack: TableNode[] = [root];
  let i = parseTag(htmlStr, start)!.end;
  /** open td cell, if any (text accumulates here; inline tags stripped) */
  let cell: TableNode | null = null;
  let cellText = '';

  const closeCell = (): void => {
    if (cell) {
      cell.content = normalizeCellText(cellText);
      cell = null;
      cellText = '';
    }
  };

  while (i < htmlStr.length) {
    const lt = htmlStr.indexOf('<', i);
    if (lt < 0) break;
    if (lt > i && cell) cellText += htmlStr.slice(i, lt);

    if (htmlStr.startsWith('<!--', lt)) {
      const end = htmlStr.indexOf('-->', lt + 4);
      if (end < 0) break;
      i = end + 3;
      continue;
    }

    const tag = parseTag(htmlStr, lt);
    if (!tag) {
      // stray '<' — treat as text
      if (cell) cellText += '<';
      i = lt + 1;
      continue;
    }
    i = tag.end;

    const name = tag.name === 'th' ? 'td' : tag.name;
    if (!STRUCTURAL.has(name)) continue; // inline tag: strip, keep text

    if (name === 'td' && !tag.closing) {
      closeCell(); // implied close of a dangling cell
      const td: TableNode = {
        tag: 'td',
        colspan: parseSpan(tag.attrs, 'colspan'),
        rowspan: parseSpan(tag.attrs, 'rowspan'),
        content: '',
        children: [],
      };
      stack[stack.length - 1].children.push(td);
      cell = td;
      cellText = '';
      continue;
    }

    // any structural open/close tag implies the end of an open cell
    closeCell();

    if (tag.closing) {
      if (name === 'td') continue; // already closed above
      let depth = -1;
      for (let s = stack.length - 1; s >= 1; s--) {
        if (stack[s].tag === name) {
          depth = s;
          break;
        }
      }
      if (depth > 0) stack.length = depth; // pop to (and including) innermost match
      if (name === 'table') break; // done with the first table
      continue;
    }

    if (name === 'table') break; // nested table start: not supported, stop
    const node: TableNode = { tag: name, colspan: -1, rowspan: -1, content: null, children: [] };
    stack[stack.length - 1].children.push(node);
    stack.push(node);
  }
  closeCell();
  return root;
}

// ---------------------------------------------------------------------------
// Zhang–Shasha exact tree edit distance
// ---------------------------------------------------------------------------

/** Flattened postorder view of a TableNode tree. */
interface Flat {
  n: number;
  tags: string[]; // 1-based
  colspan: Int32Array;
  rowspan: Int32Array;
  contents: (string | null)[];
  /** cell content split into Unicode code points (matches Python list(text)) */
  codePoints: (string[] | null)[];
  /** l[i] = postorder index of leftmost leaf descendant of node i (1-based) */
  l: Int32Array;
  keyroots: number[];
}

function flatten(root: TableNode): Flat {
  const tags: string[] = [''];
  const contents: (string | null)[] = [null];
  const colspanArr: number[] = [0];
  const rowspanArr: number[] = [0];
  const lArr: number[] = [0];

  const visit = (node: TableNode): number => {
    let leftmost = 0;
    for (let c = 0; c < node.children.length; c++) {
      const childLeftmost = visit(node.children[c]);
      if (c === 0) leftmost = childLeftmost;
    }
    tags.push(node.tag);
    colspanArr.push(node.colspan);
    rowspanArr.push(node.rowspan);
    contents.push(node.content);
    const idx = tags.length - 1;
    lArr.push(node.children.length === 0 ? idx : leftmost);
    return lArr[idx];
  };
  visit(root);

  const n = tags.length - 1;
  const l = Int32Array.from(lArr);
  // keyroots: nodes with no ancestor sharing the same leftmost leaf
  // (i.e. the highest node for each distinct l value)
  const seen = new Set<number>();
  const keyroots: number[] = [];
  for (let idx = n; idx >= 1; idx--) {
    if (!seen.has(l[idx])) {
      seen.add(l[idx]);
      keyroots.push(idx);
    }
  }
  keyroots.sort((a, b) => a - b);
  const codePoints = contents.map((c) => (c === null || c.length === 0 ? null : Array.from(c)));
  return {
    n,
    tags,
    colspan: Int32Array.from(colspanArr),
    rowspan: Int32Array.from(rowspanArr),
    contents,
    codePoints,
    l,
    keyroots,
  };
}

/** Levenshtein distance over Unicode code points (matches Python list(text)). */
function levenshtein(a: string[], b: string[]): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev = new Int32Array(n + 1);
  let cur = new Int32Array(n + 1);
  for (let j = 0; j <= n; j++) prev[j] = j;
  for (let i = 1; i <= m; i++) {
    cur[0] = i;
    const ai = a[i - 1];
    for (let j = 1; j <= n; j++) {
      const sub = prev[j - 1] + (ai === b[j - 1] ? 0 : 1);
      const del = prev[j] + 1;
      const ins = cur[j - 1] + 1;
      cur[j] = sub < del ? (sub < ins ? sub : ins) : del < ins ? del : ins;
    }
    [prev, cur] = [cur, prev];
  }
  return prev[n];
}

/** Zhang–Shasha TED between two flattened trees under the PubTabNet cost model. */
function treeEditDistance(t1: Flat, t2: Flat, structureOnly: boolean): number {
  const n1 = t1.n;
  const n2 = t2.n;
  const stride = n2 + 1;
  const td = new Float64Array((n1 + 1) * stride); // permanent tree distances
  const fd = new Float64Array((n1 + 1) * stride); // forest-distance scratch

  // rename-cost memo keyed by node-index pair (NaN = not yet computed)
  const renameCache = new Float64Array((n1 + 1) * stride).fill(NaN);
  const EMPTY: string[] = [];
  const rename = (i: number, j: number): number => {
    if (t1.tags[i] !== t2.tags[j] || t1.colspan[i] !== t2.colspan[j] || t1.rowspan[i] !== t2.rowspan[j]) return 1;
    if (t1.tags[i] === 'td' && !structureOnly) {
      const ca = t1.codePoints[i];
      const cb = t2.codePoints[j];
      if (ca === null && cb === null) return 0; // both cells empty
      const key = i * stride + j;
      let d = renameCache[key];
      if (Number.isNaN(d)) {
        const la = ca === null ? 0 : ca.length;
        const lb = cb === null ? 0 : cb.length;
        d = levenshtein(ca ?? EMPTY, cb ?? EMPTY) / Math.max(la, lb);
        renameCache[key] = d;
      }
      return d;
    }
    return 0;
  };

  const l1 = t1.l;
  const l2 = t2.l;
  for (const kr1 of t1.keyroots) {
    const li = l1[kr1];
    for (const kr2 of t2.keyroots) {
      const lj = l2[kr2];
      // forest distance over subforests rooted at kr1/kr2, offsets from li/lj
      fd[0] = 0;
      for (let x = 1, row = stride; x <= kr1 - li + 1; x++, row += stride) fd[row] = fd[row - stride] + 1;
      for (let y = 1; y <= kr2 - lj + 1; y++) fd[y] = fd[y - 1] + 1;
      for (let i1 = li, x = 1; i1 <= kr1; i1++, x++) {
        const row = x * stride;
        const prow = row - stride;
        for (let j1 = lj, y = 1; j1 <= kr2; j1++, y++) {
          const delCost = fd[prow + y] + 1;
          const insCost = fd[row + y - 1] + 1;
          if (l1[i1] === li && l2[j1] === lj) {
            const ren = fd[prow + y - 1] + rename(i1, j1);
            const best = delCost < insCost ? (delCost < ren ? delCost : ren) : insCost < ren ? insCost : ren;
            fd[row + y] = best;
            td[i1 * stride + j1] = best;
          } else {
            const bridge = fd[(l1[i1] - li) * stride + (l2[j1] - lj)] + td[i1 * stride + j1];
            fd[row + y] =
              delCost < insCost ? (delCost < bridge ? delCost : bridge) : insCost < bridge ? insCost : bridge;
          }
        }
      }
    }
  }
  return td[n1 * stride + n2];
}

/**
 * Tree-Edit-Distance-based Similarity between two table HTML strings. 0..1.
 *
 * @param predHtml predicted table HTML (a bare `<table>...</table>` fragment
 *   or any HTML containing one)
 * @param gtHtml   ground-truth table HTML
 * @param opts.structureOnly ignore cell text; score structure alone (S-TEDS)
 */
export function teds(predHtml: string, gtHtml: string, opts?: { structureOnly?: boolean }): number {
  if (!predHtml || !gtHtml) return 0;
  const pred = parseTableHtml(predHtml);
  const gt = parseTableHtml(gtHtml);
  if (!pred || !gt) return 0;

  const f1 = flatten(pred);
  const f2 = flatten(gt);
  // Reference counts table.xpath('.//*'): descendants only, root excluded.
  const denom = Math.max(f1.n - 1, f2.n - 1);
  const dist = treeEditDistance(f1, f2, opts?.structureOnly ?? false);
  if (denom <= 0) {
    // Both tables are bare <table/> nodes; the reference would divide by zero.
    return dist === 0 ? 1 : 0;
  }
  return 1 - dist / denom;
}
